### ISSUE TITLE
[Task]  Sprint00 - 기능설명

### ISSUE THREAD

**Issue by HWABAEK** [HWABAEK/Saekgalpi-ColorPalette#103]
**라벨링 하는 방법**     
E:h -> 예상 소요 시간  
Sprint00 -> 해당 스프린트  
high, middle, low -> 긴급도  
**프로젝트 추가와 마일즈스톤 추가를 해주세요**  
----------이 줄 포함 위의 내용은 삭제해주세요------------

#### 해야할 일
>  작업 내용을 적어주세요 (지워주세요)

#### 이전에 완료되어야 하는 일
>  해당 작업이 완성되기 위해서 완료되어야 하는 작업 리스트를 적어주세요 (지워주세요)
1. 
2. 
3.

**Comment by HWABAEK** [comment]
dddddd

**Comment by HWABAEK** [comment]
dddd

**Comment by lsy26499** [comment]
ㅌㅌㅌㅌ

**Comment by lsy26499** [comment]
ㄹ로
